apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: sanity-check-cron
  namespace: argo
spec:
  schedule: "*/5 * * * *"   # runs every 5 minutes
  concurrencyPolicy: "Replace"

  workflowSpec:
    entrypoint: sanity-check

    templates:
    - name: sanity-check
      container:
        image: busybox
        command: [sh, -c]
        args:
          - nc -z nats.nats.svc.cluster.local 4222 && echo "NATS OK"
