apiVersion: v1
kind: Namespace
metadata:
  name: nats
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  namespace: nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
      - name: nats
        image: nats:2.9
        ports:
        - containerPort: 4222
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  type: ClusterIP
